spring:

  # specify own properties
  datasource:
    url: 'jdbc:postgresql://localhost:5432/briene'
    password: 'postgres'
    username: 'postgres'
    driver-class-name: org.postgresql.Driver

  web:
    resources:
      static-locations: 'classpath:/'

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

  # mail still does not work - no need to specify
  mail:
    host: ${MAIL_HOST}
    port: 465
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    protocol: 'smpts'